# Generated by Django 6.1.1 on 2026-10-03 05:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_property_cam_rate_per_sqft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What the tenant reads: Water, Trash, Parking, Pruning.', max_length=100)),
                ('category', models.CharField(choices=[('UTILITY', 'Utility'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='UTILITY', help_text="Groups the charge on the tenant's statement.", max_length=16)),
                ('cycle_months', models.PositiveSmallIntegerField(default=3, help_text='How many months one bill covers. A quarterly water bill is 3.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='An inactive responsibility raises no new charges; its history stays.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibilities_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibilities', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'property responsibilities',
                'ordering': ('property__name', 'label'),
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(help_text='The first month this bill covers.')),
                ('months', models.PositiveSmallIntegerField(default=3, help_text='How many monthly charges this bill pays for.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='What the property was billed for this cycle, in dollars.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsibility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='responsibilities.propertyresponsibility')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility_cycles_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starts_on',),
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Charged every month of the cycle. Zero takes the unit out of it.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='responsibilities.responsibilitycycle')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility_shares_set', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibility_shares', to='properties.unit')),
            ],
            options={
                'ordering': ('cycle__starts_on', 'unit__identifier'),
            },
        ),
        migrations.AddConstraint(
            model_name='propertyresponsibility',
            constraint=models.UniqueConstraint(fields=('property', 'label'), name='one_responsibility_per_label'),
        ),
        migrations.AddConstraint(
            model_name='responsibilitycycle',
            constraint=models.UniqueConstraint(fields=('responsibility', 'starts_on'), name='one_cycle_per_start_date'),
        ),
        migrations.AddConstraint(
            model_name='responsibilityshare',
            constraint=models.UniqueConstraint(fields=('cycle', 'unit'), name='one_share_per_unit_per_cycle'),
        ),
    ]
