# Generated by Django 6.1.1 on 2026-10-01 00:07

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('MAINTENANCE', 'Maintenance'), ('TENANT', 'Tenant')], db_index=True, default='TENANT', help_text='Determines which parts of RHP this account may use.', max_length=20),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['username', 'created_at'], name='loginattempt_user_time'), models.Index(fields=['ip', 'created_at'], name='loginattempt_ip_time')],
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone number')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone call'), ('text', 'Text message')], default='email', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal RHP notes about this tenant. Never shown to the tenant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tenant profile',
                'verbose_name_plural': 'tenant profiles',
            },
        ),
    ]
