# Generated by Django 6.1.1 on 2026-10-02 01:08

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_superadmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text="JPEG, PNG, or WebP. Shown beside the tenant's name.", null=True, upload_to=apps.accounts.models.tenant_photo_path),
        ),
    ]
