# Generated by Django 6.1.1 on 2026-10-01 06:46

import apps.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.properties.models.property_banner_path),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial')], db_index=True, default='RESIDENTIAL', help_text='Commercial units have no bedrooms or bathrooms.', max_length=12),
        ),
    ]
