# Generated by Django 6.1.1 on 2026-10-03 05:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_type_square_feet_and_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cam_rate_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Common area maintenance per square foot, for reference.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='CAM rate per square foot'),
        ),
    ]
