# Generated by Django 6.1.1 on 2026-10-01 07:53

import apps.leases.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_unit_type_map_pin_and_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Rent per month, in dollars.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Security deposit held, in dollars. Zero if none.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rent_due_day', models.PositiveSmallIntegerField(default=1, help_text='Day of the month rent is due. A shorter month uses its last day.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ENDED', 'Ended')], db_index=True, default='DRAFT', help_text='Draft until staff activate it; ended is history and read-only.', max_length=10)),
                ('lease_file', models.FileField(blank=True, help_text='The signed lease, as a PDF or a scan. Later phases take over document handling.', null=True, upload_to=apps.leases.models.lease_document_path)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit')),
            ],
            options={
                'ordering': ('-start_date', 'unit__property__name', 'unit__identifier'),
            },
        ),
        migrations.CreateModel(
            name='LeaseTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='The primary contact for this lease.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_tenants', to='leases.lease')),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='lease_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_primary', 'tenant__first_name', 'tenant__last_name', 'tenant__username'),
            },
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status', 'end_date'], name='lease_status_end'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('unit',), name='one_active_lease_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='lease_ends_on_or_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='leasetenant',
            constraint=models.UniqueConstraint(fields=('lease', 'tenant'), name='tenant_once_per_lease'),
        ),
        migrations.AddConstraint(
            model_name='leasetenant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('lease',), name='one_primary_tenant_per_lease'),
        ),
    ]
