# Generated by Django 6.1.1 on 2026-10-03 02:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='step_up_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly increase as a fixed amount, when the lease states one instead.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='lease',
            name='step_up_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month the rent steps up, for a step-up or triple-net lease.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='lease',
            name='step_up_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly increase as a percentage: 7 means 7%.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='lease',
            name='template',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('STEP_UP', 'Step up'), ('NNN', 'Triple net (NNN)')], default='FIXED', help_text='Fixed, a once-a-year step up, or triple net — rent plus an NNN amount set each year.', max_length=10),
        ),
        migrations.AlterField(
            model_name='lease',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, help_text='Rent per month at the start of the term, in dollars.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='NnnRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='The rent due date this amount starts from.')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nnn_rates', to='leases.lease')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nnn_rates_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('effective_from',),
                'constraints': [models.UniqueConstraint(fields=('lease', 'effective_from'), name='one_nnn_rate_per_due_date')],
            },
        ),
        migrations.CreateModel(
            name='RentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='The rent due date this amount starts from.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('origin', models.CharField(choices=[('BASE', 'Starting rent'), ('STEP_UP', 'Step up'), ('MANUAL', 'Set by hand')], default='BASE', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_periods_set', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_periods', to='leases.lease')),
            ],
            options={
                'ordering': ('effective_from',),
                'constraints': [models.UniqueConstraint(fields=('lease', 'effective_from'), name='one_rent_period_per_due_date')],
            },
        ),
    ]
