# Generated by Django 6.1.1 on 2026-10-01 18:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RENT', 'Rent'), ('MANUAL', 'Manual charge'), ('ADJUSTMENT', 'Adjustment')], default='MANUAL', max_length=16)),
                ('direction', models.CharField(choices=[('INCREASE', 'Increases what is owed'), ('DECREASE', 'Reduces what is owed')], default='INCREASE', max_length=8)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField()),
                ('reason', models.CharField(blank=True, help_text='Why this entry exists. Required for adjustments.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='ledger.charge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_created', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='leases.lease')),
            ],
            options={
                'ordering': ('due_date', 'pk'),
                'indexes': [models.Index(fields=['lease', 'due_date'], name='charge_lease_due'), models.Index(fields=['kind', 'due_date'], name='charge_kind_due')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='charge_amount_is_at_least_a_cent'), models.CheckConstraint(condition=models.Q(('kind', 'ADJUSTMENT'), ('direction', 'INCREASE'), _connector='OR'), name='only_adjustments_reduce_a_charge'), models.UniqueConstraint(condition=models.Q(('kind', 'RENT')), fields=('lease', 'due_date'), name='one_rent_charge_per_month')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECEIVED', 'Payment received'), ('REVERSAL', 'Reversal')], default='RECEIVED', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('ACH', 'ACH transfer'), ('CARD', 'Card'), ('CHECK', 'Cheque'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='ACH', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('VOID', 'Void')], default='CLEARED', max_length=16)),
                ('external_reference', models.CharField(blank=True, help_text='The bank or processor reference, or a cheque number.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='leases.lease')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='ledger.payment')),
            ],
            options={
                'ordering': ('payment_date', 'pk'),
                'indexes': [models.Index(fields=['lease', 'payment_date'], name='payment_lease_date'), models.Index(fields=['status', 'payment_date'], name='payment_status_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='payment_amount_is_at_least_a_cent'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'RECEIVED'), ('reverses__isnull', True)), models.Q(('kind', 'REVERSAL'), ('reverses__isnull', False)), _connector='OR'), name='a_reversal_references_the_payment_it_reverses')],
            },
        ),
    ]
