# Generated by Django 6.1.1 on 2026-10-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, help_text='The bank or processor reference, or a check number.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ACH', 'ACH transfer'), ('CARD', 'Card'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='ACH', max_length=16),
        ),
    ]
