# Generated by Django 6.1.1 on 2026-10-03 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease_step_up_amount_lease_step_up_month_and_more'),
        ('ledger', '0002_alter_payment_external_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='kind',
            field=models.CharField(choices=[('RENT', 'Rent'), ('NNN', 'NNN'), ('MANUAL', 'Manual charge'), ('ADJUSTMENT', 'Adjustment')], default='MANUAL', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'NNN')), fields=('lease', 'due_date'), name='one_nnn_charge_per_month'),
        ),
    ]
