# Generated by Django 6.1.1 on 2026-10-03 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease_step_up_amount_lease_step_up_month_and_more'),
        ('ledger', '0003_alter_charge_kind_charge_one_nnn_charge_per_month'),
        ('responsibilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='responsibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='responsibilities.propertyresponsibility'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='kind',
            field=models.CharField(choices=[('RENT', 'Rent'), ('NNN', 'NNN'), ('RESPONSIBILITY', 'Responsibility'), ('MANUAL', 'Manual charge'), ('ADJUSTMENT', 'Adjustment')], default='MANUAL', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'RESPONSIBILITY')), fields=('lease', 'responsibility', 'due_date'), name='one_responsibility_charge_per_month'),
        ),
    ]
