# Generated by Django 6.1.1 on 2026-10-01 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LEASE_ACTIVATED', 'Lease activated'), ('LEASE_ENDED', 'Lease ended'), ('CHARGE_CREATED', 'Charge created'), ('CHARGE_ADJUSTED', 'Charge adjusted'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PAYMENT_CLEARED', 'Payment cleared'), ('PAYMENT_VOIDED', 'Payment voided'), ('PAYMENT_REVERSED', 'Payment reversed'), ('ROLE_CHANGED', 'Role changed')], max_length=32)),
                ('object_type', models.CharField(blank=True, help_text='The model an event is about, as "app.Model".', max_length=64)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Small, JSON-safe facts about the event: amounts, dates, reasons.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text="Null when the actor's account has since been removed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='leases.lease')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_target'), models.Index(fields=['lease', 'created_at'], name='audit_lease_created'), models.Index(fields=['action', 'created_at'], name='audit_action_created'), models.Index(fields=['created_at'], name='audit_created')],
            },
        ),
    ]
