# Generated by Django 6.1.1 on 2026-10-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LEASE_ACTIVATED', 'Lease activated'), ('LEASE_ENDED', 'Lease ended'), ('RENT_SCHEDULE_GENERATED', 'Rent schedule generated'), ('RENT_PERIOD_CHANGED', 'Rent period changed'), ('NNN_RATE_SET', 'NNN amount set'), ('RESPONSIBILITY_CHANGED', 'Responsibility changed'), ('RESPONSIBILITY_CYCLE_STAGED', 'Responsibility cycle staged'), ('RESPONSIBILITY_SHARES_SET', 'Responsibility shares set'), ('CHARGE_CREATED', 'Charge created'), ('CHARGE_ADJUSTED', 'Charge adjusted'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PAYMENT_CLEARED', 'Payment cleared'), ('PAYMENT_VOIDED', 'Payment voided'), ('PAYMENT_REVERSED', 'Payment reversed'), ('ROLE_CHANGED', 'Role changed')], max_length=32),
        ),
    ]
